### ISSUE TITLE
Where is FEATURED IMAGES ?

### ISSUE THREAD

**Issue by panay** [tsertkov/wp-headless#9]
In CTP UI this option exists but on the page of creating a post, it is none.

**Comment by tsertkov** [comment]
Ouch! I don't know how I could miss this issue. I am sorry for that.

I didn't know anyone other then me was using this setup. It got so much different and better since time of this issue. Stable release is expected soon and current `master` can be considered as beta. No proper readme so far.

In fact standard pages/posts content types were not supposed to be used and are even not displayed in current version admin.

Thank you for your interest in wp-headless!

**Comment by tsertkov** [comment]
Misunderstood your original question :)

With current version featured image works fine: 
![image](https://user-images.githubusercontent.com/5339042/49076382-2acdfb00-f239-11e8-8ddc-11a392b2f707.png)

**Comment by panay** [comment]
Yeah, I already did it :) Thanks!
